apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}
  labels: 
    app: {{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.postgres.port }}
  selector:
    app: {{ .Release.Name }}
    tier: database