kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.postgres.name }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.storageSize }}