apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.redis.port }}
  selector:
    app: {{ .Release.Name }}
    tier: cache