kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.redis.name }}-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.storageSize }}