{{- $db_password := .Values.postgres.db_password | required ".Values.postgres.db_password is required." -}}
{{- $rails_secret := .Values.rails_secret | required ".Values.rails_secret is required." -}}

apiVersion: v1
kind: Secret
metadata:
  name: db-user
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.postgres.db_username | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-user-pass
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password: {{ .Values.postgres.db_password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-url
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  url: {{ printf "postgres://%s:%s@%s/%s?pool=5" .Values.postgres.db_username .Values.postgres.db_password .Values.postgres.name .Values.postgres.db_name | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-key-base
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  secret-key-base: {{ .Values.rails_secret | b64enc | quote }}