{{- $db_password := .Values.postgres.db_password | required ".Values.postgres.db_password is required." -}}
{{- $rails_secret := .Values.rails_secret | required ".Values.rails_secret is required." -}}

apiVersion: v1
kind: Secret
metadata:
  name: db-user
type: Opaque
data:
  username: {{ .Values.postgres.db_username | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-user-pass
type: Opaque
data:
  password: {{ .Values.postgres.db_password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-url
type: Opaque
data:
  url: {{ "postgres://{{.Values.postgres.db_username}}:{{.Values.postgres.db_password}}@postgres/{{.Values.postgres.db_name}}?pool=5"  | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-key-base
type: Opaque
data:
  secret-key-base: {{ .Values.rails_secret | b64enc | quote }}