apiVersion: batch/v1
kind: Job
metadata:
  name: setup
  namespace: {{ .Release.Namespace }}
spec:
  completions: 1
  backoffLimit: 0
  template:
    metadata:
      name: setup
    spec:
      containers:
      - name: setup
        image: {{ .Values.app.image }}
        args: 
        - bundle 
        - exec
        - rake
        - db:create
        - db:migrate
        - db:seed
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: "db-url"
              key: "url"
        - name: RAILS_ENV
          value: "production"
        - name: SEED_ADMIN_PASSWORD
          value: "changeme"
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: "secret-key-base"
              key: "secret-key-base"
      restartPolicy: Never