apiVersion: batch/v1
kind: Job
metadata:
  name: setup
  namespace: {{ .Release.Namespace }}
  annotations:
  #   # This is what defines this resource as a hook. Without this line, the
  #   # job is considered part of the release.
    # "helm.sh/hook": post-install
    # "helm.sh/hook-weight": "-5"
    # "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  completions: 1
  template:
    metadata:
      name: setup
    spec:
      containers:
      - name: setup
        image: {{ .Values.app.image }}
        args: 
        - bundle
        - exec
        - rake
        - db:create
        - db:migrate
        - db:seed
        env:
        - name: RAILS_ENV
          value: "production"
        - name: SEED_ADMIN_PASSWORD
          value: "changeme"
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: "secret-key-base"
              key: "secret-key-base"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: "db-url"
              key: "url"
        # startupProbe:
        #   tcpSocket:
        #     port: {{ .Values.postgres.port }}
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
      restartPolicy: Never