apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Namespace }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: {{ .Values.app.name }}
              port:
                number: {{ .Values.app.port }}